### ISSUE TITLE
Change "Provider" to "Source"

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#445]
"Provider" is a confusing term, "source" is a more commonly used term that's easier to understand. Please replace all references to "provider" with "source".

**Comment by geekayush** [comment]
I have replaced all references to "provider" with "source". It is building and serving fine. On running tests, all unit tests pass but e2e tests fail. Can somebody tell why is this happening?
This is the error it is throwing.
```
> node test/e2e/runner.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/cccatalog-frontend/test/e2e/runner.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
```
